name: Build Flutter App

on:
  workflow_dispatch: # Allows manual triggering
  push:
    branches:
      - main # Runs when new code is pushed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1 # Fetch only the latest commit

      - name: Debug Folder Structure
        run: |
          echo "Current Directory:"
          pwd
          echo "List of files:"
          ls -R

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.x"

      - name: Cache Flutter Dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            build/
          key: flutter-${{ runner.os }}-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            flutter-${{ runner.os }}-

      - name: Cache Gradle Dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Ensure Android Directory Exists
        run: |
          if [ ! -d "android" ]; then
            echo "Android directory is missing! Running flutter create ."
            flutter create .
          fi

      - name: Force Update Gradle Wrapper to 8.9
        run: |
          cd android
          chmod +x gradlew
          ./gradlew wrapper --gradle-version 8.9 --distribution-type all

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: build/app/outputs/apk/release/app-release.apk
