name: Build Flutter App

on:
  repository_dispatch:
    types: [build_app]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CONFIG_JSON: ${{ toJson(github.event.client_payload.config) }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Show Directory (Debug)
        run: |
          echo "Listing root directory..."
          ls -al
          echo "Listing android/ directory..."
          ls -al android || true
          echo "Listing android/app/src/main directory..."
          ls -al android/app/src/main || true

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.5'

      - name: Flutter Clean
        run: flutter clean

      - name: Apply Configuration
        run: |
          echo "Applying configuration..."
          echo "$CONFIG_JSON" > config.json
          node scripts/applyConfig.js config.json

      - name: Get Flutter Dependencies
        run: flutter pub get

      - name: Ensure AndroidManifest is in place
        run: cp android/app/src/main/AndroidManifest.xml android/AndroidManifest.xml

      - name: Build APKs
        run: flutter build apk --release --split-per-abi --no-tree-shake-icons

      - name: Upload APK Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: flutter-apks
          path: |
            build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
            build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
            build/app/outputs/flutter-apk/app-x86_64-release.apk
