name: Build Flutter App

on:
  repository_dispatch:
    types: [build_app]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CONFIG_JSON: ${{ toJson(github.event.client_payload.config) }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache Flutter Pub Packages
        uses: actions/cache@v3
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      - name: Cache Gradle Files
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/android/build.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Show Directory (Debug)
        run: |
          echo "Listing root directory:"
          ls -al
          echo "Listing android/ directory:"
          ls -al android || true
          echo "Listing android/app/src/main directory:"
          ls -al android/app/src/main || true

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.5'

      - name: Flutter Clean
        run: flutter clean

      - name: Apply Configuration
        run: |
          echo "Applying configuration..."
          echo "$CONFIG_JSON" > config.json
          node scripts/applyConfig.js config.json

      - name: Get Flutter Dependencies
        run: flutter pub get

      - name: Ensure AndroidManifest is in place
        run: cp android/app/src/main/AndroidManifest.xml android/AndroidManifest.xml

      - name: Locate gradlew (Debug)
        run: |
          echo "Current directory:"
          pwd
          echo "Finding all gradlew files:"
          find . -name "gradlew" -type f

      - name: Flutter doctor
        run: flutter doctor -v

      - name: Recreate Android project files
        run: flutter create --platforms=android .

      - name: Build APKs
        run: flutter build apk --release --split-per-abi --no-tree-shake-icons

      - name: Upload APK Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: flutter-apks
          path: |
            build/app/outputs/apk/release/app-armeabi-v7a-release.apk
            build/app/outputs/apk/release/app-arm64-v8a-release.apk
            build/app/outputs/apk/release/app-x86_64-release.apk
            build/app/outputs/apk/release/app-release.apk  # Universal APK
