name: Build Flutter App

on:
  workflow_dispatch: # Allows manual triggering
  push:
    branches:
      - main # Runs when new code is pushed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1   # Get only latest commit to speed up

      - name: Debug Folder Structure
        run: |
          echo "Current Directory:"
          pwd
          echo "List of files:"
          ls -R

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.x"

      - name: Install Dependencies
        run: flutter pub get

      - name: Ensure Correct Working Directory
        run: |
          if [ -d "android" ]; then
            echo "Android directory exists."
          else
            echo "Android directory is missing!"
            exit 1
          fi

      - name: Prepare Gradle
        working-directory: android
        run: chmod +x gradlew && ./gradlew wrapper --gradle-version 8.0 --distribution-type all

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: build/app/outputs/apk/release/app-release.apk
